### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by borough11** [EvotecIT/Statusimo#2]
This is great, I've implemented a page on our dashboard screens. One thing I noticed was the UTC datetime from the JSON file being shown as UTC time on the page, rather than in my local system time. I'm not sure if this is the best way, but I added a few lines to the Get-StatusimoData function to convert the UTC time to the local timezone, as below...

```
function Get-StatusimoData {
    [cmdletbinding()]
    param(
        [string] $FolderPath      
    )
    if ($FolderPath -ne '' -and (Test-Path -LiteralPath $FolderPath)) {
        $Files = Get-ChildItem -LiteralPath $FolderPath    
        foreach ($File in $Files) {       
            $Output = Get-Content -LiteralPath $File.FullName -Raw | ConvertFrom-Json

            $strCurrentTimeZone = (Get-WmiObject win32_timezone).StandardName
            $TZ = [System.TimeZoneInfo]::FindSystemTimeZoneById($strCurrentTimeZone)
            $Output.PSObject.Properties | where {$_.name -like "*date*"} | ForEach-Object {
                $Output.($_.name) = [System.TimeZoneInfo]::ConvertTimeFromUtc($_.value, $TZ)
            }

            $Output | Add-Member -Name 'FullName' -Value $File.FullName -MemberType NoteProperty -Force
            $Output
        }
    } 
}
```

Now the dates in the Timeline and Scheduled Maintenance sections match my system time. If there's a better way, please let us know :)

Thanks for the great module!

Cheers,
Steve.

**Comment by PrzemyslawKlys** [comment]
This is now fixed. Thank you for reporting this. It seems saving to JSON saves it as UTC and loading as UTC as well. Applied your fix. 

Make sure to:
```
Update-Module PSWriteHTML
Update-Module Statusimo
```

PSWriteHTML was also updated to support better features. Here's changelog

  -  Fix for TimeZone issue being UTC (thanks Steve (borough11)
  -  Updates to support changes in PSWriteHTML (requires newest version of PSWriteHTML 0.0.13+)
  -  Small visual change to TimeLine (using Roboto font, a bit larger size)
  -  Cleaner HTML/JS/CSS (update to PSWriteHTML)
  -  Smaller output size (update to PSWriteHTML)
