### ISSUE TITLE
not able to use Splat with "New-StatusimoPage" command

### ISSUE THREAD

**Issue by Tonic8** [EvotecIT/Statusimo#3]
Hello

following the example, i wanted to use the splat function with the command New-StatusimoPage

$newstatusimopage = @{
	FilePath		= "$chemin\index.html"
	IncidentsPath	= "$chemin\Incidents"
	MaintenancePath	= "$chemin\Maintenance"
}

New-StatusimoPage @$newstatusimopage

the result is a file where the powershell prompt is named "@System.Collections.Hashtable" that represent the html file 😄 

while all the other command are ok.

Thanks a lot.

**Comment by PrzemyslawKlys** [comment]
```powershell
New-StatusimoPage @newstatusimopage
```
Not 

```powershell
New-StatusimoPage @$newstatusimopage
```

**Comment by Tonic8** [comment]
and...... i'am very very sorry!. ☹️ 

not the first time i do this mistake 🤦 

usually i have red warning saying missing parameter 😄  but the command was getting out with no message.

Thanks and again sorry.
