### ISSUE TITLE
Alignement with new PSwriteHTML

### ISSUE THREAD

**Issue by red-erik** [EvotecIT/Statusimo#6]
Hello,
thank you for this software. Very useful.
Is it still maintained and update with new PSwriteHTML module ?

Regards,
Red.

**Comment by PrzemyslawKlys** [comment]
There's no reason it would fail, but I haven't checked in a while. The cmdlets in PSWriteHTML retained the functionality. Is there a p[roblem with it?

**Comment by red-erik** [comment]
Hello,
nope and thank you for checking. This is exactly what I was looking for. The evolution would be to be able to modify the "status" (so json files) directly through Web interface.
Regards,
Red.

**Comment by red-erik** [comment]
Thanks
